name: Go tests

on:
  dispatch:
  pull_request:
  push:
    paths:
      - '**/*.go'
      - '*.go'
      - 'go.*'

jobs:
  build:
    runs-on: alpine-tools
    steps:
      - uses: actions/checkout@v7
      - name: go test
        id: go-test
        run: |
          go test
