name: Go tests

on:
  dispatch:
  push:
    paths:
      - '**/*.go'
      - '*.go'
      - 'go.*'

jobs:
  build:
    runs-on: alpine-tools
    steps:
      - name: go test
        id: go-test
        run: |
          go test
